### PR TITLE
browser based upload - generation of presigned fields

### PR DESCRIPTION
**Pull request by tajchumber**
I've added a couple of functions that generate presigned fields for browser based uploads as explained here in the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html)

Please let me know what you think :)

### CODE REVIEW

**Comment by tajchumber** [comment]
ping @benwilson512 😃

**Comment by angelo-moreira** [comment]
@benwilson512  this would be great to have so I don't need to do it on my app :+1:

**Comment by baldwindavid** [comment]
@tajchumber - I might be doing it wrong, but this seems very opinionated about the generated policy. The way I'm trying to use it is for cases where a form takes a file, but I don't already know the mimetype or key. I would generally want to be able to ensure that the policy allows a list of content types and a key that "starts with" a given path. I also want to add a "success_action_status" so that S3 returns a 201 upon a successful upload. All that is to say, is this too opinionated for the types of policies that others would need?

Either way, the code in this PR is helpful to me as it was quite easy to take it and modify for my needs. Thanks for that!

**Comment by baldwindavid** [comment]
@tajchumber - Here is an example of what I'm using based on your code. By default the policy enforces that a key starts with the specified path and provides for passing additional fields... https://gist.github.com/baldwindavid/0516131d9a768d57c96af0fd98206e7d

**Comment by tajchumber** [comment]
@baldwindavid I perfectly understand what you mean here
In the next few days I'll improve the code taking in consideration your requirements as well!

**Comment by baldwindavid** [comment]
@tajchumber - By default, my policy is now setting a max size requirement based upon a configurable max size option (https://gist.github.com/baldwindavid/0516131d9a768d57c96af0fd98206e7d#file-s3_direct-ex-L137). This is an example of why it's hard to set a default that everyone could agree on.

**Pull request closed without merging**
